### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by swiftxy** [liuyanhongwl/ios_common#1]
我用的你的demo, 我申请了测试证书. NWPusher  push 是成功的.

我采取了,将扩展  Run UserNotification这个APP上, 但是我的.m 文件的断点根本不允许.
我的扩展是按照这样处理的.
```
{
     "aps":{
     	 "alert":"Testing.. (35)",
	  "badge":1,
    	 "sound":"default",
	 "mutable-content":1
	  }
}
```
我想问下这种问题该怎么解决?

**Comment by liuyanhongwl** [comment]
@yinjialiang1993 你好，关于extension的调试，如果是ContentExtension，需要在运行时选择要调试的target。
如果是ServiceExtension，需要去`Debug -> Attach to process by pID or name`，填写相应的target。
[请参考这里](https://github.com/liuyanhongwl/ios_common/blob/master/files/App-Extension-Tips.md)

**Comment by swiftxy** [comment]
恩恩, 我这边是Build phases 配置的问题
